### ISSUE TITLE
when executing "rails g lines:install": undefined method 'assets'  

### ISSUE THREAD

**Issue by gibso** [opoloo/lines-engine#33]
hey there,

i use ruby 2.5.3 and rails 5.2.2
i added `gem 'lines-engine'` to my Gemfile, but when i try to execute `rails g lines:install` in my shell i get the following error:

```
/Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/railtie/configuration.rb:97:in `method_missing': undefined method `assets' for #<Rails::Application::Configuration:0x00007f9e3038bcf8>
Did you mean?  asset_host (NoMethodError)
	from /Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/lines-engine-1.2.6.1/config/initializers/assets.rb:1:in `<main>'
	from /Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	from /Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	from /Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `block in load'
	from /Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `load'
	from /Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/engine.rb:657:in `block in load_config_initializer'
	from /Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/notifications.rb:170:in `instrument'
	from /Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/engine.rb:656:in `load_config_initializer'
	from /Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
	from /Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/engine.rb:613:in `each'
	from /Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/engine.rb:613:in `block in <class:Engine>'
	from /Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
	from /Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/hoou17009/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	from /Users/hoou17009/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/hoou17009/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/hoou17009/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/hoou17009/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/initializable.rb:50:in `each'
	from /Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/initializable.rb:50:in `tsort_each_child'
	from /Users/hoou17009/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:415:in `call'
	from /Users/hoou17009/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /Users/hoou17009/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/hoou17009/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `each'
	from /Users/hoou17009/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `call'
	from /Users/hoou17009/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/hoou17009/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	from /Users/hoou17009/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	from /Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
	from /Users/hoou17009/hoou_dev/iris/config/environment.rb:5:in `<main>'
	from /Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from /Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	from /Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	from /Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/application.rb:102:in `preload'
	from /Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
	from /Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
	from /Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
	from /Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
	from /Users/hoou17009/.rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/hoou17009/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Users/hoou17009/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from -e:1:in `<main>'
```

Maybe my Rails-Version is not compatibe? Which one do you suggest?

**Comment by jfacoustic** [comment]
Any errors on your bundle install?  Or have you figured it out by now?  
Sorry, I'm just starting to contribute to this project.
